// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// distanceToPeakCpp
NumericVector distanceToPeakCpp(NumericVector distance, NumericVector rho);
RcppExport SEXP densityClust_distanceToPeakCpp(SEXP distanceSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(distanceToPeakCpp(distance, rho));
    return rcpp_result_gen;
END_RCPP
}
// findDistValueByRowColInd
NumericVector findDistValueByRowColInd(NumericVector distance, size_t num_row, NumericVector row_inds, NumericVector col_inds);
RcppExport SEXP densityClust_findDistValueByRowColInd(SEXP distanceSEXP, SEXP num_rowSEXP, SEXP row_indsSEXP, SEXP col_indsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< size_t >::type num_row(num_rowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type row_inds(row_indsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type col_inds(col_indsSEXP);
    rcpp_result_gen = Rcpp::wrap(findDistValueByRowColInd(distance, num_row, row_inds, col_inds));
    return rcpp_result_gen;
END_RCPP
}
// gaussianLocalDensity
NumericVector gaussianLocalDensity(NumericVector distance, size_t nrow, double dc);
RcppExport SEXP densityClust_gaussianLocalDensity(SEXP distanceSEXP, SEXP nrowSEXP, SEXP dcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< size_t >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< double >::type dc(dcSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussianLocalDensity(distance, nrow, dc));
    return rcpp_result_gen;
END_RCPP
}
// nonGaussianLocalDensity
NumericVector nonGaussianLocalDensity(NumericVector distance, size_t nrow, double dc);
RcppExport SEXP densityClust_nonGaussianLocalDensity(SEXP distanceSEXP, SEXP nrowSEXP, SEXP dcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< size_t >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< double >::type dc(dcSEXP);
    rcpp_result_gen = Rcpp::wrap(nonGaussianLocalDensity(distance, nrow, dc));
    return rcpp_result_gen;
END_RCPP
}
