// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// distanceToPeakCpp
NumericVector distanceToPeakCpp(NumericVector distance, NumericVector rho);
RcppExport SEXP densityClust_distanceToPeakCpp(SEXP distanceSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    __result = Rcpp::wrap(distanceToPeakCpp(distance, rho));
    return __result;
END_RCPP
}
// gaussianLocalDensity
NumericVector gaussianLocalDensity(NumericVector distance, int nrow, double dc);
RcppExport SEXP densityClust_gaussianLocalDensity(SEXP distanceSEXP, SEXP nrowSEXP, SEXP dcSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< double >::type dc(dcSEXP);
    __result = Rcpp::wrap(gaussianLocalDensity(distance, nrow, dc));
    return __result;
END_RCPP
}
// nonGaussianLocalDensity
NumericVector nonGaussianLocalDensity(NumericVector distance, int nrow, double dc);
RcppExport SEXP densityClust_nonGaussianLocalDensity(SEXP distanceSEXP, SEXP nrowSEXP, SEXP dcSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< double >::type dc(dcSEXP);
    __result = Rcpp::wrap(nonGaussianLocalDensity(distance, nrow, dc));
    return __result;
END_RCPP
}
