# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distanceToPeakCpp <- function(distance, rho) {
    .Call('densityClust_distanceToPeakCpp', PACKAGE = 'densityClust', distance, rho)
}

gaussianLocalDensity <- function(distance, nrow, dc) {
    .Call('densityClust_gaussianLocalDensity', PACKAGE = 'densityClust', distance, nrow, dc)
}

nonGaussianLocalDensity <- function(distance, nrow, dc) {
    .Call('densityClust_nonGaussianLocalDensity', PACKAGE = 'densityClust', distance, nrow, dc)
}

